// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhmwwpqvxhaljsqfxuqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlobXd3cHF2eGhhbGpzcWZ4dXFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMTYwOTgsImV4cCI6MjA2MTY5MjA5OH0.d6stAgeAJIZCi0K1KzrQetVo3zQ8_t0VvzO39WD3CX4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);